services:
  - type: worker
    name: wa-reminder-agent
    env: node
    buildCommand: apt-get install -y chromium-browser --no-install-recommends && npm install
    startCommand: node --max-old-space-size=256 src/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
